
local_directory: "D:\\PyHEIS_Data"
online_directory: "https://s3.ir-thr-at1.arvanstorage.com/gsmedb/HEIS"

defult_first_year: 1363
defult_last_year: 1400

# can be csv or sql
storage_technology: csv

defult_map: humandata